@Service
public class SqlSolverService {

    public String buildFinalQuery() {

        return "SELECT d.DEPARTMENT_NAME AS DEPARTMENT_NAME, ROUND(AVG(YEAR(CURDATE()) - YEAR(e.DOB)), 2) AS AVERAGE_AGE, GROUP_CONCAT(CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) ORDER BY e.EMP_ID SEPARATOR ', ') AS EMPLOYEE_LIST FROM EMPLOYEE e JOIN DEPARTMENT d ON e.DEPARTMENT = d.DEPARTMENT_ID JOIN PAYMENTS p ON e.EMP_ID = p.EMP_ID WHERE p.AMOUNT > 70000 GROUP BY d.DEPARTMENT_ID ORDER BY d.DEPARTMENT_ID DESC LIMIT 10";
    }
}
